### ISSUE TITLE
Som kund vill jag få uppdateringar via e-post  om min leveransstatus

### ISSUE THREAD

**Issue by EVettainen** [Project-Rika/Rika_OrderProvider#6]
![Image](https://github.com/user-attachments/assets/167e0e5f-563f-42d1-83eb-3da6d65723e9)

### **Tasks:**
- [ ] Skapa en service som genererar ett bekräfelsemejl
---
- [ ] Skicka bekräftelsemejl med servicebus till queue "email_request"
---

### **Testfallsbeskrivningar:**

- [ ] Testfall 1: Bekräftelsemejl skickas om ordern har skapats

_Förutsättningar:_
- En order har skapats och ett orderId samt kunden e-post finns tillgängliga

_Steg:_
- Skicka en POST-förfrågan till /api/orders som skapar en ny order
- Ett bekräftelsemejl skapas baserat på orderId och e-post

_Förväntat resultat:_
- API retunerar statuskod 201 Created
- Ett bekräftelsemejl skickas till kön "email_request" via servicebus
- Ingen återkoppling krävs från EmailProvider

---

- [ ] Testfall 2: Bekräfelsemejl skickas inte om ordern inte skapas

_Förutsättningar:_
- Ordern skapas inte på grund av valideringsfel i requesten och returnerar 400 Bad Request.

_Steg:_
- Skicka en POST-förfrågan till /api/orders med ett JSON-objekt som saknar nödvändiga fält eller har ett felaktigt format

_Förväntat resultat:_
- API retunerar statuskod 400 Bad Request 
- Inget bekräftelsemejl genereras
- Ingen vidare interaktion sker med servicebus och emailprovider

---

- [ ] Testfall 3: Kommunikationen med servicebus misslyckas, men ordern skapas

_Förutsättningar:_
- Ett kommunikationsfel uppstår med ServiceBus, men ordern skapats korrekt.

_Steg:_
- Skicka en POST-förfrågan till /api/orders som resulterar i en lyckad order men simulera ett kommunikationsfel med servicebus.

_Förväntat resultat:_
- API returnerar 201 Created
- Ordern sparas korrekt i databasen.
- Ett fel loggas för misslyckad kommunikation med servicebus
- Ingen vidare interaktion sker med servicebus och emailprovider

---

### **Acceptanskriterier:**

- [ ] Bekräftelsemejl genereras endast efter lyckad order
- [ ] Inget bekräftelsemejl vid misslyckad order
- [ ] Om kommunikationen med servicebus misslyckas, ska ordern fortfarande skapas
